baseURL: https://zhenghe.hu
title: Zheng He Hu
Author: 
  name: Zheng He Hu
theme: tale-hugo
disablePathToLower: true
enableGitInfo: true
enableEmoji: true
menu:
  main:
  - identifier: notes
    name: Notes
    url: /notes/
    weight: 0